/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiChalkboardRouteImport } from './routes/api/chalkboard'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppQuizRouteImport } from './routes/_app.quiz'
import { Route as AppLearnRouteImport } from './routes/_app.learn'
import { Route as AppGameRouteImport } from './routes/_app.game'
import { Route as AppFlashcardsRouteImport } from './routes/_app.flashcards'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChalkboardRoute = ApiChalkboardRouteImport.update({
  id: '/api/chalkboard',
  path: '/api/chalkboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizRoute = AppQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnRoute = AppLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AppRoute,
} as any)
const AppGameRoute = AppGameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => AppRoute,
} as any)
const AppFlashcardsRoute = AppFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/flashcards': typeof AppFlashcardsRoute
  '/game': typeof AppGameRoute
  '/learn': typeof AppLearnRoute
  '/quiz': typeof AppQuizRoute
  '/settings': typeof AppSettingsRoute
  '/api/chalkboard': typeof ApiChalkboardRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/flashcards': typeof AppFlashcardsRoute
  '/game': typeof AppGameRoute
  '/learn': typeof AppLearnRoute
  '/quiz': typeof AppQuizRoute
  '/settings': typeof AppSettingsRoute
  '/api/chalkboard': typeof ApiChalkboardRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/flashcards': typeof AppFlashcardsRoute
  '/_app/game': typeof AppGameRoute
  '/_app/learn': typeof AppLearnRoute
  '/_app/quiz': typeof AppQuizRoute
  '/_app/settings': typeof AppSettingsRoute
  '/api/chalkboard': typeof ApiChalkboardRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/flashcards'
    | '/game'
    | '/learn'
    | '/quiz'
    | '/settings'
    | '/api/chalkboard'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/flashcards'
    | '/game'
    | '/learn'
    | '/quiz'
    | '/settings'
    | '/api/chalkboard'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/onboarding'
    | '/_app/flashcards'
    | '/_app/game'
    | '/_app/learn'
    | '/_app/quiz'
    | '/_app/settings'
    | '/api/chalkboard'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  ApiChalkboardRoute: typeof ApiChalkboardRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chalkboard': {
      id: '/api/chalkboard'
      path: '/api/chalkboard'
      fullPath: '/api/chalkboard'
      preLoaderRoute: typeof ApiChalkboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quiz': {
      id: '/_app/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof AppQuizRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learn': {
      id: '/_app/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AppLearnRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/game': {
      id: '/_app/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof AppGameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flashcards': {
      id: '/_app/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof AppFlashcardsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppFlashcardsRoute: typeof AppFlashcardsRoute
  AppGameRoute: typeof AppGameRoute
  AppLearnRoute: typeof AppLearnRoute
  AppQuizRoute: typeof AppQuizRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFlashcardsRoute: AppFlashcardsRoute,
  AppGameRoute: AppGameRoute,
  AppLearnRoute: AppLearnRoute,
  AppQuizRoute: AppQuizRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  ApiChalkboardRoute: ApiChalkboardRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
